# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Applying Gateway API YAML's
        run: |
          currentdate=$(date +"%d%m%Y") && echo $currentdate &&
          cat /Users/vejairaj/CKA-learning/CKA-preparation/Gateway-API/1-Basic-Gateway-API/. > applied.yaml
          echo "The Above files are apllied for the pipeline" >>applied.yaml
         
    


  
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Applying Gateway API YAML's
        run: |
          kubectl apply -f /Users/vejairaj/CKA-learning/CKA-preparation/Gateway-API/1-Basic-Gateway-API/.
          currentdate=$(date +"%d%m%Y") && echo $currentdate
          kubectl get all > $currentdate.log
          
          echo "Deployment complete" 
